name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (example for Node.js project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}

      - name: Load Secrets into Environment
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          doppler secrets download --no-file --format env > secrets.env
          set -o allexport
          source secrets.env
          set +o allexport

      - name: Use Secrets Insecurely
        run: |
          echo "Building application with a visible secret..."

          echo "SECRET_KEY: $SECRET_KEY"  # Небезопасно: ключ отображается в логах!

          export DATABASE_URL="postgresql://user:$SECRET_KEY@localhost:5432/mydatabase"
          echo "Connecting to the database using DATABASE_URL: $DATABASE_URL"  # Небезопасно: полный URL в логах!

          if [ -f "./run_database_migrations.sh" ]; then
            ./run_database_migrations.sh --db-url=$DATABASE_URL
          else
            echo "Migration script not found. Skipping migrations."
          fi
        env:
          SECRET_KEY: $SECRET_KEY
