name: CI/CD for API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies for testing
        run: |
          pip install -r lab_3/requirements-test.txt

      - name: Build and run containers
        run: |
          docker compose -f ./lab_3/docker-compose.yml up -d --build

      - name: Verify running containers
        run: |
          docker ps

      - name: Verify API availability
        run: |
          sleep 2 
          curl -f http://localhost:8000/api/hash_code?s=test || exit 1

      - name: Run API tests
        run: |
          pytest ./lab_3/tests.py --verbose
