name: Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (example for Node.js project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          echo "Deployment step would be added here."
          curl -Ls https://cli.doppler.com/install.sh | sudo sh
          doppler setup --token ${{ secrets.DOPPLER_TOKEN }} --project lab-3 --config dev_personal
          doppler secrets download --format=env --output .doppler.env
          source .doppler.env
          echo "Secrets loaded successfully."
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no user@your-server.com "echo 'Deployment started.'"
